### ISSUE TITLE
Remove dependency on specific Qiskit versions by MQTBench

### ISSUE THREAD

**Issue by archanaravindar** [cda-tum/MQTBench#133]
MQTBench(Version: 0.1.5.dev6+gfa71205)
 depends on specific versions of Qiskit as the versions are pinned by the requirements file.
That would make it difficult to use MQTBench with evolving versions of Qiskit, can these pins please be removed.

**Comment by nquetschlich** [comment]
@archanaravindar: thanks for opening this issue. We are planning to upgrade the dependencies within the next weeks.
