### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by nquetschlich** [cda-tum/MQTBench#24]
- [x] Prevent website from refreshing after pressing the Download Button (and # of selected benchmarks: 0) to not erase the current config
- [x] Add hint that the zip file generation takes up to 15min
- [x] At the moment the resizing seems a bit off though, as the text is just scaled to a smaller size without changing line breaks and such. -> Text Size shouldn't be shrinked that much
- [x] The hyperlinks should be with the describing part of the sentences and not "this page"
- [x] zip file for the case where all files are selected could be pre-generated
- [x] Implement the UI Improvements such that it is oriented more towards the levels

**Comment by burgholzer** [comment]
In addition to the last case: we could provide several pre-generated zip-files for the most-commonly used scenarios.

**Comment by nquetschlich** [comment]
solved in #93
