### ISSUE TITLE
Improvement on zip file handling

### ISSUE THREAD

**Issue by nquetschlich** [cda-tum/MQTBench#26]
- Currently, each click on the download button on our website triggers the server to create a new zip file with the selected benchmarks.
- Since many files may be selected, this process of creating the zip file can take up to 30min and the user has to wait.
- A desired solution would be, that the user will be somehow notified, that the server finished creating the zip and is provided by means to access it.

- [x] A first step could be to pre-generate the zip for all possible benchmarks
- [ ] A second step could be that the created zip file is stored either on the server or somewhere external and the user is provided with a download link

**Comment by nquetschlich** [comment]
The first task is now implemented

**Comment by hillmich** [comment]
Related to #36

**Comment by hillmich** [comment]
I think the second checkbox is obsolete, should this ticket be closed?
