### ISSUE TITLE
Remove Benchmarks from Repository and Rewrite History

### ISSUE THREAD

**Issue by hillmich** [cda-tum/MQTBench#53]
Currently there are around 40k benchmarks  (OpenQASM files) saved in this repository, requiring about 30GB space in the working directory. The cloning is also pretty nasty.

We should remove the benchmarks and rewrite the history so new clones are faster. 

Fixing this issue also requires adjustment of the workflow for server deployment, since the ZIP file cannot be created anymore (and, thus, not be sync'ed to the server).

**Comment by hillmich** [comment]
[filter-repo](https://github.com/newren/git-filter-repo) seems like a good tool to do the job.

It's probably a good idea to delete all merged (and unnecessary) [branches](https://github.com/cda-tum/MQTBench/branches/all) before the rewrite.

**Comment by burgholzer** [comment]
A history rewrite has been performed. A fresh clone now takes approximately 2.1MiB 🥳
