### ISSUE TITLE
Make Benchmark Generation Reproducible

### ISSUE THREAD

**Issue by hillmich** [cda-tum/MQTBench#55]
The generation of benchmarks is currently not reproducible. Two changes should enable reproducible generation

1. [x] Set a seed for the transpiler (Qiskit supports this, I don't know about tket)
2. [x] Fix the versions in Python dependencies (explicitly use `==` instead of `~=`)

Bonus: Check the actually required packages for bench and benchviewer (and delete not required packages).

**Comment by nquetschlich** [comment]
solved in #93
