### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by nquetschlich** [cda-tum/MQTBench#59]
To improve the versioning of MQT Bench, the following task should be implemented:

- [x] Instead of creating the ZIP using the GitHub actions, a ZIP should be added to each release
- [x] The workflow for publishing updates of the UI without a newly created ZIP file needs to be adapted
- [x] Benchviewer should be part of the pypi package such that it may be executed locally (also very important for reproducing a certain MQT Bench version). The viewer and the ZIP file may be optional dependencies for the pypi package.

**Comment by hillmich** [comment]
We can use the [LZMA](https://docs.python.org/3/library/zipfile.html#zipfile.ZIP_LZMA) compresion algorithm for the zip as well. In a brief test, this reduces the size of the whole archive from 1.4GB to 0.7GB compared to the current [deflated](https://docs.python.org/3/library/zipfile.html#zipfile.ZIP_DEFLATED) algorithm. For the generated zip in the viewer, we should still use deflated though, as LZMA compression is way slower. Decompression seems to be neglectably slower.

**Comment by nquetschlich** [comment]
solved in #93
